# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get Git Tag
      id: git_tag
      run: echo "::set-output name=tag::$(git describe --abbrev=0 --tags)"
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Gradle
      run: cmd /r gradlew.bat build
    # - name: create UI distribution
    #   run: gradle distZip
          # Add a step to fetch the Git tags
    - name: Archive jars
      uses: actions/upload-artifact@v2
      with:
        name: firo-artifacts
        path: |
         FIRO_TSEnsembles/build/libs
         firoplugin/build/libs
         ensemble-dss/build/libs
         ensemble-view/build/distributions
    - name: Publish package
      uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
      with:
          arguments: publish
      env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
